### ISSUE TITLE
Time labels overlap for 1h availability durations [Low-Priority]

### ISSUE THREAD

**Issue by giraugh** [GRA0007/crab.fit#1]
When there is only a hour gap between the two controls on the availability slider, the time labels overlap. Perhaps just some additiona padding or a special-case style for this could be a fix?

<img width="194" alt="Screen Shot 2021-03-05 at 2 52 33 pm" src="https://user-images.githubusercontent.com/16392483/110065082-809f8f00-7dc2-11eb-9221-2da1f9c8a52d.png">

**Comment by GRA0007** [comment]
Fixed in #2 😀
