### ISSUE TITLE
Wrong licensing in backend's package.json

### ISSUE THREAD

**Issue by MaySoMusician** [GRA0007/crab.fit#107]
**Describe the bug**
MIT License is wrongly specified in crabfit-backend package.json. 

**Expected behavior**
The license should be declared as `GPL-3.0-only` (or `GPL-3.0-or-later` if you want, though you haven't added 'or any later version' phrase into README)

**Comment by GRA0007** [comment]
Good catch! I think that was set from the yarn init, and I never changed it
