### ISSUE TITLE
Adjust heatmap gradient/colors to make 'better' options stand out more

### ISSUE THREAD

**Issue by rpophessagr** [GRA0007/crab.fit#116]
With larger group sizes, it can be hard to distinguish the single-color gradient. The 'highlight highest availability' feature and hover-to-show-availability is very helpful! But sometimes there may not be enough of the 'best' option, so I might want to look at runners-up.

For me, the distinctions between the top few options is more important than the least-available options. For instance, if 14-17 of the 17 people invited can attend, I'd like to see those distinctions more clearly, whereas if only 3 vs 4 people are going to attend, I don't really care about the distinction since I'm not going to schedule it then anyways.

It would be helpful for the color gradient to reflect that (i.e. use 5 distinct shades for the top 5 options and white/grey for everything else, or plot as white up to, say, the 75th percentile, and then gradient above there, or, skew the heat map to add more distinct shades at the higher response percentages). 

Another option would be to use multiple colors, like a red-yellow-green stoplight (though I guess that's not great for colorblind users... and the monochrome scheme is cute)

Happy to discuss if the issue/proposed solution isn't clear! Screenshot attached of an example where it's hard to see good options.
![crabfit](https://user-images.githubusercontent.com/32719557/132894210-e826b92c-b380-44ca-866a-e8dec8630281.png)

**Comment by GRA0007** [comment]
This is great feedback! I think your idea to skew the colours to show more of a difference with the higher availabilities is a good idea, I might also look into providing some different colour palettes to choose from, maybe red through green for example.
