### ISSUE TITLE
Can't see hours when too far horizontally

### ISSUE THREAD

**Issue by agaget** [GRA0007/crab.fit#129]
A picture is better than 1000 words:
![image](https://user-images.githubusercontent.com/25428659/156399005-ad13fa52-7b17-45cb-8c06-cd1f8a7b6d55.png)

I have to guess wich hours i'm choosing for the last 2 weeks.

One solution can be to add hours for all the weeks.

![image](https://user-images.githubusercontent.com/25428659/156399548-a2bf22ff-3eec-41ea-bb8b-6489080d3ad8.png)

**Comment by GRA0007** [comment]
Thanks @agaget! This is a good suggestion!
