### ISSUE TITLE
Select all and invert selection

### ISSUE THREAD

**Issue by agaget** [GRA0007/crab.fit#130]
I had to fullfill one crabfit with my touchpad on my laptop : it was painful !

If we can select the whole day with one click it would already be easier.

Thanks

**Comment by GRA0007** [comment]
You can tap and drag to select a range, so this may not be a high priority, but I'll keep it in mind, thanks.

**Comment by altsalt** [comment]
The way I've seen this implemented on other platforms is by clicking on the date title itself. Perhaps clicking and dragging horizontally could select multiple entire days.

**Comment by GRA0007** [comment]
Thanks @altsalt, I'll look into it, if there's a way I can implement that solution without compromising accessibility then I'll do it :)
