### ISSUE TITLE
Option to mark levels of preference for times

### ISSUE THREAD

**Issue by wolftune** [GRA0007/crab.fit#131]
See whenisgood.net — crab.fit is the first thing I've seen that functions like it at all (and specifically is Free/Libre/Open) thank you thank you thank you!

The specific feature missing is the ability to mark availability at 3 levels: possible, fine, best.

At whenisgood.net, those are slightly different colors, and you click the level and then drag with that level, click a different level to mark that. You can test this yourself. Whenisgood currently has no payment processing, so if you make an account and click to pay $20, it will just instead say "sorry, payment not working now, here's a free pro account" and then you can see the multiple-level preference function.

**Comment by GRA0007** [comment]
Thanks @wolftune, Crab Fit is currently designed to be as simple as possible, but if I can find an intuitive way of adding this feature I'll do it!

**Comment by wolftune** [comment]
Thanks! If you do what I said about getting a pro account at whenisgood, you can see how it manages this with a very small and clean UI.

**Comment by altsalt** [comment]
This feature is the main reason I have continued to recommend whenisgood and I'd love to see it included here!

The UI of having different gradients of boxes on the side that change which one you are entering with seems to function well enough.

**Comment by GRA0007** [comment]
Hey @wolftune and @altsalt, I believe this will add too much complexity to a simple site like Crab Fit, so I've decided not to go ahead with this feature.

I can understand why as a responder you might want to indicate which times are "best" as opposed to "available but prefer not to be", however in most cases if you'd really rather not be available at that time you can just leave it empty. I like that the simple UI forces you to think about exactly when you are available for the specific event, and not simply put in your waking hours sans any other events etc.

Additionally, there are plenty of other services (like whenisgood) that do provide this extra functionality if required, as well as other features (like adding comments when submitting availability). Crab Fit is designed primarily to work in tandem with everything else you already use, by doing one thing really well, rather than replacing as much as it can.

The way I use Crab Fit is usually in a group chat with friends, and if I need to supplement my availability with a comment, or let them know that a particular day in my availability is tentative, then I'll just do that directly in chat alongside the Crab Fit link.

**Comment by wolftune** [comment]
@GRA0007 have you actually tried http://whenisgood.net/ with this option? You can get free access as I described initially here. If you haven't tried using it, then you are speculating about the idea of too much complexity. As someone who has used it at whenisgood often and with other people, I really want to insist that this is *not* too much complexity and is very very useful.

When people are organizing times, *some* people have the attitude and personality to just say "no" to any times they'd "rather not" do, but that can create problems because times that they would do if pressed aren't known and sometimes the result is picking a time they absolutely can't do (because no time they prefer is actually good for others).

You might like just being more clear and binary about yes/no availability, but I imagine that's because it works for your sort of schedule, life, and personality. Many other people have more flexible availability and are too hesitant to say no, and they will mark availability for all the times they are at all willing to do, and the result then is that such people can be pushed to do less-preferred times when a much better option was in fact feasible but nobody knew that such a preference existed.

Whenisgood is not FLO! It can't be changed or updated as software, it isn't even on a secure website. It will probably break and disappear forever sometime.

I accepted your other closure of #136 without comment, so I want to highlight how different I feel about this issue specifically.

Would you please consider at least leaving this open with something like a "help needed" tag? Even if you won't consider adding this yourself, could we please actively invite other potential contributors to work on it? This is not complex in the UI and it *is* extremely valuable and accommodating to people with different personalities and life circumstances.

**Comment by GRA0007** [comment]
@wolftune yes, I did try it so I am not speculating. By complexity I mean not only the mental complication, but also finding a place in the UI to put these levels, as well as the fact that the current data storage method would be incompatible. Not to mention that on whenisgood, extra symbols on the times are required to show the multiple levels of availability.

<img width="426" alt="image" src="https://github.com/GRA0007/crab.fit/assets/8862273/4fafb79a-1f36-4b12-a409-66edeab44491">

I understand that whenisgood is not open source and that's a big plus for some,

**Comment by wolftune** [comment]
"not open source" is a big *minus*, not a plus, I assume that was a writing error though

Framadate is nothing like crabfit or whenisgood, framadate's UI is much more clunky and limiting. Framadate does not provide anything that serves the functionality I'm describing from whenisgood. It is nothing like crabfit.

The extra symbols on whenisgood with the red dots are unrelated extra visualizations of availability which do not relate to this point about preference levels. The use of variable color seems simple enough.

The Whenisgood approach essentially considers any level of availability as "available", it just allows the levels for investigation. So, even if the UI mostly did not show them, people considering options can look at any specific participant and see their preferences for reference.

**Comment by FreeScholar** [comment]
My first thought would be to see if anyone wants to make it happen on a branch as well as other optional features that are only visible via a tiny link to "more features" and keep the default display lean without extra feature  text, arrows etc.  adding clutter to the eye.

The reason I like this feature is my disability. I do not always know if I will be able to keep an appointment - so - I want people to be aware of my  flakiness.  After a 2 hr conference I am sometimes energized and sometimes drained - during a long day, I never know how I will be, minute to minute. There are days or times when I can be more certain.

**Comment by drinkablebreeze** [comment]
@wolftune [Here you go!](https://github.com/GRA0007/crab.fit/issues/307#issuecomment-1879525884)

**Comment by wolftune** [comment]
wowow thanks! You must be reading my mind to go in this direction with the request!

Now if just #132 #134 and #137 were done, we'd have a feature-complete replacement of WhenIsGood…
