### ISSUE TITLE
Some description text field for events and each respondent

### ISSUE THREAD

**Issue by wolftune** [GRA0007/crab.fit#132]
As in whenisgood.net feature: Offer the ability to provide a longer text description for events so that people can express notes about it.

Also, an optional text field for each responder so they can make whatever statement that may be helpful. For example, "I'm available any time, so I just marked the times I prefer" or "On Thursday, I can attend, but I'll have to be calling in remotely" or whatever.

And then when looking at results, when hovering over specific people, their comment text would be shown.

**Comment by GRA0007** [comment]
I think this might be too much unnecessary info to display and may cause the layout to become cluttered. Event descriptions can be communicated in an email or message along with the link, but thank you for the suggestion!

**Comment by altsalt** [comment]
I'd love to have comments for respondents at very least. The ability to hover over a response and see additional (optional) details on the same page as the poll would be quite valuable as someone who organizes a many things.
