### ISSUE TITLE
Consider not making request to Google automatically

### ISSUE THREAD

**Issue by wolftune** [GRA0007/crab.fit#133]
For those who might be extra privacy-sensitive (but not enough to be running a zillion blocking plugins or who run them and look at tools critically based on how many requests are blocked), I suggest tweaking the calendar integrations.

What if instead of making the third-party request to Google automatically, the button was programmed to only start the request and connection to Google *after* someone clicks the button?

Also the request to Google Tag Manager is not ideal in this respect

**Comment by GRA0007** [comment]
This is a good suggestion, currently Crab Fit checks every time so you don't have to re-login if you already have before, but I might make this and the analytics a preference that users can toggle on/off.

**Comment by GRA0007** [comment]
This has been addressed in #259!

Once deployed, Google scripts will _only_ be loaded after clicking the calendar sync button. Additionally, Google Analytics has been replaced with Vercel analytics.
