### ISSUE TITLE
Feature request: Privacy controls

### ISSUE THREAD

**Issue by wolftune** [GRA0007/crab.fit#134]
There could be situations where an organizer wants to see all the results but not allow the attendees to see one another's availability or even names. For that situation, it would be ideal if there were a way to make an event so that someone has to log in with a passphrase or to use a distinct URL in order to view results, separate from the link shared with attendees for putting in their availability.

Just another of the things that whenisgood.net does that would get crab.fit to be a complete replacement.

I am so thrilled to discover crab.fit. I've been wishing for *years* that someone would do this or that whenisgood would free their source under a FLO license.

**Comment by GRA0007** [comment]
This is outside the scope of Crab Fit, but I am working on another product that may fulfil this requirement.
