### ISSUE TITLE
Request: Limiting a poll to selected range

### ISSUE THREAD

**Issue by wolftune** [GRA0007/crab.fit#136]
In whenisgood.net, this is basically a master poll that is used as the template. So, besides choosing days and overall time range, an initial drag-of-times sets the boundaries for when anyone else can even mark.

The value is for limiting to a set of possibilities when the poll creator knows there's no reason to have anyone answer outside of those.

**Comment by GRA0007** [comment]
Thanks for the request @wolftune! This is a good idea, although probably not a priority at the moment as it may increase the complexity of creating an event without much benefit. I will look into it though.

**Comment by wolftune** [comment]
Yeah, I'd probably have a check-box of something like "limit responses further?" or similar, and checking that makes the "master poll" show up in the make-poll UI. I would agree that it shouldn't show up by default.

**Comment by altsalt** [comment]
This may be related to #114 in that there are unavailable/available blocks the poll creator likely has. Thus, asking for responses during those unavailable periods is a waste of energy.

**Comment by GRA0007** [comment]
Hey thanks again for the feature request, I agree that this could be useful, however to simplify the creation process, I've decided against implementing it, as I think being able to specify days and times is good enough. :)
