### ISSUE TITLE
Persistent user accounts

### ISSUE THREAD

**Issue by altsalt** [GRA0007/crab.fit#137]
**Is your feature request related to a problem? Please describe.**
I schedule dozens of events per week and would like to have a single place to access all of the results. Additionally, it would be nice to be able to delete polls of past events to avoid data clutter. Finally, I would like to be able to select whether poll results are viewable by others.

**Describe the solution you'd like**
All of these problems will require some sort of persistent account with a dashboard and access controls.

**Describe alternatives you've considered**
Currently I continue to rely on a non-FLO tool, whenisgood. I can resolve the first of my three problems with a sidecar text file.

**Additional context**
This is clearly a larger feature and it would be nice if there could be some community input, perhaps in the form of UI mockups and development. Perhaps multiple issues to track different components would be appropriate. Starting with this one as I don't personally have the brainwidth and appreciate your efforts and vision.

**Comment by altsalt** [comment]
Going through some of the closed issues, this relates to #134 and #32 and maybe #132 

Thanks for your work on this project, really excited to have a FLO alternative to one of my daily use tools!

**Comment by GRA0007** [comment]
Hey thanks for this request @altsalt. I actually plan on doing something exactly like this at https://crab.watch (shh), but currently I'm focused on making Crab Fit as good as it can be for its use case. It will likely be some time until Crab Watch is actualised, but keep an eye out, it's something I would also really like to use as well.
