### ISSUE TITLE
"If Need Be" Scheduling Option Request

### ISSUE THREAD

**Issue by gcassel** [GRA0007/crab.fit#139]
**Is your feature request related to a problem? Please describe.**
I love the general UI of crabfit, but it apparently does not enable users to indicate non-preferred time slots with "if need be" (or an equivalent).  Some other scheduling apps have this option, and some of my groups use it regularly.

**Describe the solution you'd like**
I'd like users to be able to toggle their inputs for time slots and ranges through _yes_, _if need be_ and _no_ options.  This could be technically implemented for single time slots by enabling users to repeatedly left-click those slots to toggle their input through all three options.  It seems trickier to combine that feature with the current ability to "drag and select" a sequence of time slots together, but there are at least a couple of potential workarounds:  

1. Enabling a repeat of the same _drag and select_ operation to toggle from _yes_ to _if need be_ to _no_.  (This could be tricky however for a person with an imprecise mouse or motor skills.)
2.  Enabling a right-click on a previously selected sequence of time slots to toggle that sequence's status.

**Comment by altsalt** [comment]
Related to #131
