### ISSUE TITLE
Add ability to delete polls

### ISSUE THREAD

**Issue by peterkaminski** [GRA0007/crab.fit#140]
**Is your feature request related to a problem? Please describe.**

My presenting problem is that I have a poll that is turned out to incorrect and is now obsolete (I created a new, correct poll), but no way to communicate that to the visitors to the poll.  I wish I could delete the poll, so visitors would not find an [attractive nuisance](https://en.wikipedia.org/wiki/Attractive_nuisance_doctrine) there (en.wikipedia.org, explaining the concept of "attractive nuisance).

Separately but similarly, it would be nice to be able to manually delete polls of past events to avoid data clutter, as mentioned in #137.

**Describe the solution you'd like**

- The system remembers who created the poll, with a password-based login. (Similar to #137.)
- The person who created the poll can sign in, and click a "Delete This Poll" button. After confirmation, the poll is deleted.  Future visitors to the poll would see a message, "This poll has been deleted by the creator." Perhaps they would not see any details of the old poll, or perhaps they would, depending on UX preference.  Optionally, it is still listed in the creator's "recent polls" list, but with "[deleted]" prepended to the title.

An optional, nice-to-have feature: the creator can identify a new poll that replaces the deleted poll.  Perhaps there would be a checkbox near the delete button that said, "Create a new poll to replace this one", and then upon deletion, visitors to the original poll see a link leading to the new poll.  On deletion, the creator would be directed to create the new poll.  The UX workflow for this feature, and corner cases involved (such as, creator fails to complete new poll creation) would add some complexity to easy deletion, so maybe it's not worth doing.

**Describe alternatives you've considered**

I reposted my original polling request with the URL of the new, corrected poll URL. This is not completely effective, because one of the places I posted the URL was to a Zoom chat, which will persist, but which I cannot correct. So it's possible the old URL will still receive visitors.

**Additional context**

Possibly related to:

- #137 (contemplates need for "creator view" of polls)
- #32 (contemplates some additional features needed for poll deletion)

**Comment by GRA0007** [comment]
Thanks for the request @peterkaminski. I know the feeling when I realise I've made a mistake creating a Crab Fit and I need to create a new one, however this is out of scope for this project. I want to keep complexity to a minimum, and this would require some form of actual authentication.
Currently Crab Fit operates on a "no-trust" basis; once an event is created, there is no way of editing or deleting the event. I have plans for a future product that may alleviate this issue but for now Crab Fit won't have any user accounts or event editing features.
