### ISSUE TITLE
No calendar options shown on Chromium - "Invalid Dates" shown instead

### ISSUE THREAD

**Issue by naikymen** [GRA0007/crab.fit#234]
**Describe the bug**

No calendar options are shown on Chromium when voting. An "Invalid Dates" notice is shown instead.

It works correctly in Firefox.

**To Reproduce**
1. Open Chromium
2. Go to a crab.fit
3. See the error
4. Open Firefox, the error does not appear.

**Expected behavior**

Voting options should appear

**Screenshots**

Chromium (all extensions disabled):

![image](https://user-images.githubusercontent.com/3259326/200904966-4f421468-3aa4-4fa7-8346-3b9661738e04.png)

Firefox:

![image](https://user-images.githubusercontent.com/3259326/200905377-e6fa0172-c3cf-4f55-a580-3276e61bb65a.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser chromium
 - Version Chromium 107.0.5304.87 Arch Linux

**Comment by infinisil** [comment]
I cannot reproduce this problem, even with the very same chromium version. Reproducible with Nix:

```
nix-store -r /nix/store/ncvf6slv6n03g991rq1n50zs76cklmpz-chromium-107.0.5304.87
/nix/store/ncvf6slv6n03g991rq1n50zs76cklmpz-chromium-107.0.5304.87/bin/chromium
```

However, I can reproduce this with Firefox versions below 110. In particular 109.0.1 fails in the same way as this issue, but 110.0.1 works. To reproduce the problem:
```
nix-store -r /nix/store/hpccyic6pxqrwd56pqzz2rxrr9i13pmj-firefox-109.0.1
/nix/store/hpccyic6pxqrwd56pqzz2rxrr9i13pmj-firefox-109.0.1/bin/firefox
```

It works with 110.0.1:

```
nix-store -r /nix/store/sicgrrym8gpzh5nxbmkv0n05xr8yw37b-firefox-110.0.1
/nix/store/sicgrrym8gpzh5nxbmkv0n05xr8yw37b-firefox-110.0.1/bin/firefox
```

**Comment by GRA0007** [comment]
Hey @naikymen and @infinisil, I've just deployed a full rewrite of Crab Fit that uses a new library to handle dates. If you get a chance would you be able to try and reproduce this issue with the latest version?

**Comment by infinisil** [comment]
I can confirm that it's fixed! Thanks a lot!

**Comment by naikymen** [comment]
It works wonderfully, thanks a lot for the fix and the awesome app :)

**Comment by GRA0007** [comment]
Hooray! Thanks for checking :D
