### ISSUE TITLE
Toggle to select in calendar "free time" or "busy time"

### ISSUE THREAD

**Issue by fedorvinogradov** [GRA0007/crab.fit#236]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to choose between selecting your free time or your busy time

**Describe alternatives you've considered**
Can't think of alternatives

**Additional context**
Some people don't have a lot of meetings, so it is easier to select busy time rather than free time slots

**Comment by GRA0007** [comment]
Thanks for the suggestion @fedorvinogradov! I'm going to tackle this in #130, as being able to invert the selection should resolve this.
