### ISSUE TITLE
Hovering over names of attendees causes application error

### ISSUE THREAD

**Issue by nobnap** [GRA0007/crab.fit#270]
### Description of the bug

Hello!
When attempting to hover over the names of participants, the browser shows error `Application error: a client-side exception has occurred (see the browser console for more information).`
Console shows error `TypeError: l is undefined`.

I have tested this with multiple crab fit events, using both Firefox and Edge (both have the same issue) and multiple other people have confirmed that this is also happening to them.

Thanks in advance!

### To reproduce

1. Go to a crab fit event
2. Hover over one of the participants' names

**Comment by GRA0007** [comment]
Hey @nobnap, thanks for reporting this! I can't seem to replicate it on my machine by following the steps you've provided, is this happening with a particular event?

**Comment by nobnap** [comment]
Hey, I have done some further testing and it seems to only be happening to events with more than 5 participants? It happens in this event I created for example: https://crab.fit/testevent-623163. I tested on  two different computers and it happened in both only after I added the fifth person.

**Comment by awesome-Leni** [comment]
The same issue has happened to me with 4 participants already.
Google console shows the following:
![image](https://github.com/GRA0007/crab.fit/assets/11368819/5b704e8f-79a8-495b-9225-e7a0764d86b9)

**Comment by GRA0007** [comment]
Thanks for this! I'll try and get this resolved as soon as I can 🫡

**Comment by GRA0007** [comment]
Thanks again @nobnap and @awesome-Leni, I've pushed a fix for this which should resolve the crashing, let me know if it's still happening for you :)
