### ISSUE TITLE
https://api.crab.fit/docs is down...

### ISSUE THREAD

**Issue by ppom0** [GRA0007/crab.fit#275]
... but is linked here: https://github.com/GRA0007/crab.fit/blob/ba4cb919bd54d47deb028a87698654a2249cf5fb/api/README.md

I don't know whether the url has changed or something is really down.

**Comment by GRA0007** [comment]
Hey @ppom0, sorry for the confusion! Currently https://api.crab.fit is the old API, and I plan to swap it over to the new one very soon (possibly this weekend). For now, you can access the API docs at https://v3.api.crab.fit/docs, I suppose I future-proofed too much haha!

I'll leave this issue open till I update the URL just in case anyone else comes across the same issue.

**Comment by GRA0007** [comment]
Ok! I've updated the URL now, so you should be able to access the docs at https://api.crab.fit/docs. I'll be taking down the v3 version in a few days :)

**Comment by ppom0** [comment]
Great, thank you! We're looking forward to host the service at picasoft.net :)
