### ISSUE TITLE
Deploy a second API instance as a failsafe

### ISSUE THREAD

**Issue by TadeSF** [GRA0007/crab.fit#286]
### Description of the bug

When I open my recently created polls (created 14h ago or so), I don't get any data even though I know people have already put in their information. Also, I am unable to sign up or sign in, an arbitrary error message is displayed.

The only way I can imagine is that there is a server problem. Response time of the website is very slow, which is also weird.

### To reproduce

1. Go to a poll page
2. Try to add you name
3. Click Login
4. Error Message should be displayed and nothing else happens

### Expected behavior

This is pretty obvious, my data should be displayed and I should be able to log in.

### Additional information

I hope this helps and that you can fix the issue at hand without too much effort.
I love crab fit and I am recommending it at least twice a day these days, but since I am running an important and time sensitive poll, the situation leaves me a little bit nervous.
All the best and thanks for the great tool!

**Comment by GRA0007** [comment]
Hey @TadeSF, I'm so sorry this happened, looks like my host for the API had an issue and it went down. I'm upset it happened while I was asleep as well, sorry it's been down for so long!

It should be back up and working again now. I'm going to investigate methods to prevent this from happening again.

**Comment by Midas-sudo** [comment]
> Hey @TadeSF, I'm so sorry this happened, looks like my host for the API had an issue and it went down. I'm upset it happened while I was asleep as well, sorry it's been down for so long!
> 
> It should be back up and working again now. I'm going to investigate methods to prevent this from happening again.

I believe it happen again. Can't create new events nor login on to old ones. And it seems that old events are not loading the availability.

**Comment by GRA0007** [comment]
Thanks @Midas-sudo. I believe fly.io is having some issues today. I've restarted it again.

**Comment by Midas-sudo** [comment]
![image](https://github.com/GRA0007/crab.fit/assets/69457730/27710b41-8713-46c5-8a0c-e63aff6402c8)
Could it be better to have the min number of instances at 1?

**Comment by GRA0007** [comment]
Thanks @Midas-sudo, but I want it to scale down to 0 when not being used to reduce costs on my end. That's not the issue here though. I'm going to try adding a `restart_limit` which should attempt to restart the API if it fails.

**Comment by Midas-sudo** [comment]
> Thanks @Midas-sudo, but I want it to scale down to 0 when not being used to reduce costs on my end. That's not the issue here though. I'm going to try adding a `restart_limit` which should attempt to restart the API if it fails.

Yea,I guess that if no one is using it should be off 😅 

U already know if you need help I'm glad to do so 😄

**Comment by GRA0007** [comment]
@Midas-sudo, thanks, your support is really appreciated 🌻 
I've set it up to scale to three different regions now so hopefully that will provide some redundancy and also speed it up for people from other parts of the world.

**Comment by GRA0007** [comment]
Deploying to multiple regions seems to have resolved this for now. Let's hope we don't encounter any more issues with availability.
