### ISSUE TITLE
Days in pre-existing poll disappeared

### ISSUE THREAD

**Issue by ejm554** [GRA0007/crab.fit#299]
### Description of the bug

I've set up a poll about three weeks ago that let people offer their general availability for a seven-day week. The results displayed as expected until today, when I noticed that it was only showing results for three days, i.e., Sat, Sun, and Mon. The other four days were no longer displaying. See screenshot.

### To reproduce

1. In a web browser, go to a pre-existing days-of-the-week poll that normally shows all seven days in a week.
2. Notice that it only displays three days.

### Expected behavior

I expected it to show all seven days like it normally does.

### Device info:
OS: Windows 10 Pro 19045.3208
Browser: Google Chrome Version 115.0.5790.110 

---

### Screenshot:
![image](https://github.com/GRA0007/crab.fit/assets/26723535/0df043d0-b513-43af-9033-e85a765a2db7)

**Comment by heyitsao** [comment]
My friends and I have also been having this issue, using Firefox and Chrome. The grid doesn't show up at all if we create a new poll with only the days Monday - Friday (no weekends). We've been having this issue since yesterday, 7/30/2023, and it's been very frustrating as we rely on Crab.Fit for quite a few things.

**Comment by ejm554** [comment]
Update: Now it's no longer showing _any_ days of the week.

![image](https://github.com/GRA0007/crab.fit/assets/26723535/d4cdeb9d-e4eb-4074-823b-aa2ce050d086)

**Comment by GRA0007** [comment]
Thanks for the report y'all. Looks like there's a bug for weekday events, we're on it now.
